version: '2.0'
services:
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"